name: Run Tests on Multiple OS



on:
  push:
    branches:
      - main 

jobs:
  test-macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Go to 2-3-4 ex
        run: cd 2-3-4-Exercises
      - name: Install dependencies
        run: npm ci  
      - name: Run tests
        run: npm run test  

  test-ubuntu:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/setup-node@v4
        with: 
          node-version: '22.x'
      - name: Go to 2-3-4 ex
        run: cd 2-3-4-Exercises
      - name: Install dependencies
        run: npm ci  
      - name: Run tests
        run: npm run test  