name: Run Tests on Multiple OS

on:
  push:
    branches:
      - main 

jobs:
  test-macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Pobiera kod repozytorium

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'  # Ustawia wersję Node.js

      - name: Install dependencies
        run: |
          cd 2-3-4-Exercises
          npm ci
      - name: Run tests
        run: | 
          npm run test  
        working-directory: 2-3-4-Exercises

  test-ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Pobiera kod repozytorium

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'  # Ustawia wersję Node.js

      - name: Install dependencies
        run: |
          cd 2-3-4-Exercises
          npm ci
      - name: Run tests
        run: | 
          cd 2-3-4-Exercises
          npm run test  