name: Run Tests on Multiple OS



on:
  push:
    branches:
      - main 

jobs:
  test-macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: |
          cd 2-3-4-Exercises
          npm ci
          npm run test
      - name: Run tests
        run: | 
          cd 2-3-4-Exercises
          npm run test  
        working-directory: 2-3-4-Exercises

  test-ubuntu:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/setup-node@v4
        with: 
          node-version: '22.x'
      - name: Install dependencies
        run: |
          cd 2-3-4-Exercises
          npm ci
          npm run test
      - name: Run tests
        run: | 
          cd 2-3-4-Exercises
          npm run test  